

dynbind( c("csound64","csound","csnd64","lib_csnd64.dylib","csound64Lib","csoundLib"), "
csoundAddSpinSample(*<CSOUND_>iif)v;
csoundAppendOpcode(*<CSOUND_>*cii*c*c*p*p*p)i;
csoundCfgErrorCodeToString(i)*c;
csoundChanIASet(*<CSOUND_>*fi)i;
csoundChanIASetSample(*<CSOUND_>iif)i;
csoundChanIKSet(*<CSOUND_>fi)i;
csoundChanIKSetValue(*<CSOUND_>if)i;
csoundChanOAGet(*<CSOUND_>*fi)i;
csoundChanOAGetSample(*<CSOUND_>ii)f;
csoundChanOKGet(*<CSOUND_>*fi)i;
csoundChanOKGetValue(*<CSOUND_>i)f;
csoundCleanup(*<CSOUND_>)i;
csoundCloseLibrary(*v)i;
csoundCompile(*<CSOUND_>i**c)i;
csoundCreate(*v)*<CSOUND_>;
csoundCreateBarrier(I)*v;
csoundCreateConfigurationVariable(*<CSOUND_>*c*vii*v*v*c*c)i;
csoundCreateGlobalVariable(*<CSOUND_>*cJ)i;
csoundCreateMutex(i)*v;
csoundCreateThread(*p*v)*v;
csoundCreateThreadLock()*v;
csoundDeleteCfgVarList(**<csCfgVariable_u>)v;
csoundDeleteChannelList(*<CSOUND_>*<CsoundChannelListEntry_>)v;
csoundDeleteConfigurationVariable(*<CSOUND_>*c)i;
csoundDeleteUtilityList(*<CSOUND_>**c)v;
csoundDestroy(*<CSOUND_>)v;
csoundDestroyBarrier(*v)i;
csoundDestroyGlobalVariable(*<CSOUND_>*c)i;
csoundDestroyMessageBuffer(*<CSOUND_>)v;
csoundDestroyMutex(*v)v;
csoundDestroyThreadLock(*v)v;
csoundDisposeOpcodeList(*<CSOUND_>*<opcodeListEntry>)v;
csoundEnableMessageBuffer(*<CSOUND_>i)v;
csoundGet0dBFS(*<CSOUND_>)f;
csoundGetAPIVersion()i;
csoundGetCPUTime(*<RTCLOCK_S>)d;
csoundGetChannelLock(*<CSOUND_>*ci)*i;
csoundGetChannelPtr(*<CSOUND_>**f*ci)i;
csoundGetControlChannelParams(*<CSOUND_>*c*f*f*f)i;
csoundGetCurrentThreadId()*v;
csoundGetDebug(*<CSOUND_>)i;
csoundGetEnv(*<CSOUND_>*c)*c;
csoundGetFirstMessage(*<CSOUND_>)*c;
csoundGetFirstMessageAttr(*<CSOUND_>)i;
csoundGetHostData(*<CSOUND_>)*v;
csoundGetInputBuffer(*<CSOUND_>)*f;
csoundGetInputBufferSize(*<CSOUND_>)j;
csoundGetKr(*<CSOUND_>)f;
csoundGetKsmps(*<CSOUND_>)i;
csoundGetLibrarySymbol(*v*c)*v;
csoundGetMessageCnt(*<CSOUND_>)i;
csoundGetMessageLevel(*<CSOUND_>)i;
csoundGetNamedGens(*<CSOUND_>)*v;
csoundGetNchnls(*<CSOUND_>)i;
csoundGetOutputBuffer(*<CSOUND_>)*f;
csoundGetOutputBufferSize(*<CSOUND_>)j;
csoundGetOutputFileName(*<CSOUND_>)*c;
csoundGetRandomSeedFromTime()I;
csoundGetRealTime(*<RTCLOCK_S>)d;
csoundGetRtPlayUserData(*<CSOUND_>)**v;
csoundGetRtRecordUserData(*<CSOUND_>)**v;
csoundGetSampleFormat(*<CSOUND_>)i;
csoundGetSampleSize(*<CSOUND_>)i;
csoundGetScoreOffsetSeconds(*<CSOUND_>)f;
csoundGetScoreTime(*<CSOUND_>)d;
csoundGetSizeOfMYFLT()i;
csoundGetSpin(*<CSOUND_>)*f;
csoundGetSpout(*<CSOUND_>)*f;
csoundGetSpoutSample(*<CSOUND_>ii)f;
csoundGetSr(*<CSOUND_>)f;
csoundGetStrVarMaxLen(*<CSOUND_>)i;
csoundGetTable(*<CSOUND_>**fi)i;
csoundGetUtilityDescription(*<CSOUND_>*c)*c;
csoundGetVersion()i;
csoundInitTimerStruct(*<RTCLOCK_S>)v;
csoundInitialize(*i***ci)i;
csoundInitializeCscore(*<CSOUND_>*<__sFILE>*<__sFILE>)i;
csoundInputMessage(*<CSOUND_>*c)v;
csoundIsScorePending(*<CSOUND_>)i;
csoundJoinThread(*v)J;
csoundKeyPress(*<CSOUND_>c)v;
csoundListChannels(*<CSOUND_>**<CsoundChannelListEntry_>)i;
csoundListConfigurationVariables(*<CSOUND_>)**<csCfgVariable_u>;
csoundListUtilities(*<CSOUND_>)**c;
csoundLocalizeString(*c)*c;
csoundLockMutex(*v)v;
csoundLockMutexNoWait(*v)i;
csoundMessage(*<CSOUND_>*c?)v;
csoundMessageS(*<CSOUND_>i*c?)v;
csoundMessageV(*<CSOUND_>i*c*c)v;
csoundNewOpcodeList(*<CSOUND_>**<opcodeListEntry>)i;
csoundNotifyThreadLock(*v)v;
csoundOpenLibrary(**v*c)i;
csoundParseConfigurationVariable(*<CSOUND_>*c*c)i;
csoundPerform(*<CSOUND_>)i;
csoundPerformBuffer(*<CSOUND_>)i;
csoundPerformKsmps(*<CSOUND_>)i;
csoundPerformKsmpsAbsolute(*<CSOUND_>)i;
csoundPopFirstMessage(*<CSOUND_>)v;
csoundPreCompile(*<CSOUND_>)i;
csoundPvsinSet(*<CSOUND_>*<pvsdat_ext>i)i;
csoundPvsoutGet(*<CSOUND_>*<pvsdat_ext>i)i;
csoundQueryConfigurationVariable(*<CSOUND_>*c)*<csCfgVariable_u>;
csoundQueryGlobalVariable(*<CSOUND_>*c)*v;
csoundQueryGlobalVariableNoCheck(*<CSOUND_>*c)*v;
csoundQueryInterface(*c**v*i)i;
csoundRand31(*i)i;
csoundRandMT(*<CsoundRandMTState_>)I;
csoundRegisterSenseEventCallback(*<CSOUND_>*p*v)i;
csoundRemoveCallback(*<CSOUND_>*p)v;
csoundReset(*<CSOUND_>)v;
csoundRewindScore(*<CSOUND_>)v;
csoundRunCommand(**ci)j;
csoundRunUtility(*<CSOUND_>*ci**c)i;
csoundScoreEvent(*<CSOUND_>c*fj)i;
csoundScoreExtract(*<CSOUND_>*<__sFILE>*<__sFILE>*<__sFILE>)i;
csoundScoreSort(*<CSOUND_>*<__sFILE>*<__sFILE>)i;
csoundSeedRandMT(*<CsoundRandMTState_>*II)v;
csoundSetCallback(*<CSOUND_>*p*vI)i;
csoundSetChannelIOCallback(*<CSOUND_>*p)v;
csoundSetConfigurationVariable(*<CSOUND_>*c*v)i;
csoundSetControlChannelParams(*<CSOUND_>*cifff)i;
csoundSetCscoreCallback(*<CSOUND_>*p)v;
csoundSetDebug(*<CSOUND_>i)v;
csoundSetDrawGraphCallback(*<CSOUND_>*p)v;
csoundSetExitGraphCallback(*<CSOUND_>*p)v;
csoundSetExternalMidiErrorStringCallback(*<CSOUND_>*p)v;
csoundSetExternalMidiInCloseCallback(*<CSOUND_>*p)v;
csoundSetExternalMidiInOpenCallback(*<CSOUND_>*p)v;
csoundSetExternalMidiOutCloseCallback(*<CSOUND_>*p)v;
csoundSetExternalMidiOutOpenCallback(*<CSOUND_>*p)v;
csoundSetExternalMidiReadCallback(*<CSOUND_>*p)v;
csoundSetExternalMidiWriteCallback(*<CSOUND_>*p)v;
csoundSetFileOpenCallback(*<CSOUND_>*p)v;
csoundSetGlobalEnv(*c*c)i;
csoundSetHostData(*<CSOUND_>*v)v;
csoundSetHostImplementedAudioIO(*<CSOUND_>ii)v;
csoundSetInputValueCallback(*<CSOUND_>*p)v;
csoundSetIsGraphable(*<CSOUND_>i)i;
csoundSetKillGraphCallback(*<CSOUND_>*p)v;
csoundSetKillXYinCallback(*<CSOUND_>*p)v;
csoundSetLanguage(i)v;
csoundSetMakeGraphCallback(*<CSOUND_>*p)v;
csoundSetMakeXYinCallback(*<CSOUND_>*p)v;
csoundSetMessageCallback(*<CSOUND_>*p)v;
csoundSetMessageLevel(*<CSOUND_>i)v;
csoundSetOutputValueCallback(*<CSOUND_>*p)v;
csoundSetPlayopenCallback(*<CSOUND_>*p)v;
csoundSetReadXYinCallback(*<CSOUND_>*p)v;
csoundSetRecopenCallback(*<CSOUND_>*p)v;
csoundSetRtcloseCallback(*<CSOUND_>*p)v;
csoundSetRtplayCallback(*<CSOUND_>*p)v;
csoundSetRtrecordCallback(*<CSOUND_>*p)v;
csoundSetScoreOffsetSeconds(*<CSOUND_>f)v;
csoundSetScorePending(*<CSOUND_>i)v;
csoundSetYieldCallback(*<CSOUND_>*p)v;
csoundSleep(J)v;
csoundStop(*<CSOUND_>)v;
csoundTableGet(*<CSOUND_>ii)f;
csoundTableLength(*<CSOUND_>i)i;
csoundTableSet(*<CSOUND_>iif)v;
csoundUnlockMutex(*v)v;
csoundWaitBarrier(*v)i;
csoundWaitThreadLock(*vJ)i;
csoundWaitThreadLockNoTimeout(*v)v;
")
cstruct("
CSOUND_{};
RTCLOCK_S{ll}starttime_real starttime_CPU ;
csCfgVariableBoolean_s{*<csCfgVariable_u>*C*iii*C*C}nxt name p type flags shortDesc longDesc ;
csCfgVariableDouble_s{*<csCfgVariable_u>*C*dii*C*Cdd}nxt name p type flags shortDesc longDesc min max ;
csCfgVariableFloat_s{*<csCfgVariable_u>*C*fii*C*Cff}nxt name p type flags shortDesc longDesc min max ;
csCfgVariableHead_s{*<csCfgVariable_u>*C*vii*C*C}nxt name p type flags shortDesc longDesc ;
csCfgVariableInt_s{*<csCfgVariable_u>*C*iii*C*Cii}nxt name p type flags shortDesc longDesc min max ;
csCfgVariableMYFLT_s{*<csCfgVariable_u>*C*fii*C*Cff}nxt name p type flags shortDesc longDesc min max ;
csCfgVariableString_s{*<csCfgVariable_u>*C*cii*C*Ci}nxt name p type flags shortDesc longDesc maxlen ;
csRtAudioParams{*ciiiiif}devName devNum bufSamp_SW bufSamp_HW nChannels sampleFormat sampleRate ;
opcodeListEntry{*c*c*c}opname outypes intypes ;
pvsdat_ext{iiiiiiiI*f}N sliding NB overlap winsize wintype format framecount frame ;
")
cunion("
csCfgVariable_u|<csCfgVariableHead_s><csCfgVariableInt_s><csCfgVariableBoolean_s><csCfgVariableFloat_s><csCfgVariableDouble_s><csCfgVariableMYFLT_s><csCfgVariableString_s>}h i b f d m s ;
")
CSFTYPE_AIFC=13;
CSFTYPE_AIFF=12;
CSFTYPE_ATS=41;
CSFTYPE_AU=15;
CSFTYPE_AVR=21;
CSFTYPE_CAF=20;
CSFTYPE_CVANAL=39;
CSFTYPE_EXTRACT_PARMS=9;
CSFTYPE_FLAC=19;
CSFTYPE_FLOATS_BINARY=52;
CSFTYPE_FLOATS_TEXT=51;
CSFTYPE_FTABLES_BINARY=49;
CSFTYPE_FTABLES_TEXT=48;
CSFTYPE_HETRO=36;
CSFTYPE_HRTF=44;
CSFTYPE_HTK=22;
CSFTYPE_IMAGE_PNG=59;
CSFTYPE_INTEGER_BINARY=54;
CSFTYPE_INTEGER_TEXT=53;
CSFTYPE_IRCAM=11;
CSFTYPE_LADSPA_PLUGIN=46;
CSFTYPE_LORIS=42;
CSFTYPE_LPC=40;
CSFTYPE_MAT4=23;
CSFTYPE_MAT5=24;
CSFTYPE_MIDI_SYSEX=35;
CSFTYPE_NIST=25;
CSFTYPE_OPTIONS=8;
CSFTYPE_ORCHESTRA=2;
CSFTYPE_ORC_INCLUDE=4;
CSFTYPE_OTHER_BINARY=58;
CSFTYPE_OTHER_TEXT=57;
CSFTYPE_PAF=26;
CSFTYPE_POSTSCRIPT=55;
CSFTYPE_PVC=37;
CSFTYPE_PVCEX=38;
CSFTYPE_PVF=27;
CSFTYPE_RAW_AUDIO=10;
CSFTYPE_SCORE=3;
CSFTYPE_SCORE_OUT=6;
CSFTYPE_SCOT=7;
CSFTYPE_SCO_INCLUDE=5;
CSFTYPE_SCRIPT_TEXT=56;
CSFTYPE_SD2=16;
CSFTYPE_SDIF=43;
CSFTYPE_SDS=28;
CSFTYPE_SNAPSHOT=47;
CSFTYPE_SOUNDFONT=33;
CSFTYPE_STD_MIDI=34;
CSFTYPE_SVX=29;
CSFTYPE_UNIFIED_CSD=1;
CSFTYPE_UNKNOWN=0;
CSFTYPE_UNKNOWN_AUDIO=32;
CSFTYPE_VOC=30;
CSFTYPE_VST_PLUGIN=45;
CSFTYPE_W64=17;
CSFTYPE_WAVE=14;
CSFTYPE_WAVEX=18;
CSFTYPE_XI=31;
CSFTYPE_XSCANU_MATRIX=50;
CSLANGUAGE_AFRIKAANS=1;
CSLANGUAGE_ALBANIAN=2;
CSLANGUAGE_ARABIC=3;
CSLANGUAGE_ARMENIAN=4;
CSLANGUAGE_ASSAMESE=5;
CSLANGUAGE_AZERI=6;
CSLANGUAGE_BASQUE=7;
CSLANGUAGE_BELARUSIAN=8;
CSLANGUAGE_BENGALI=9;
CSLANGUAGE_BULGARIAN=10;
CSLANGUAGE_CATALAN=11;
CSLANGUAGE_CHINESE=12;
CSLANGUAGE_COLUMBIAN=72;
CSLANGUAGE_CROATIAN=13;
CSLANGUAGE_CZECH=14;
CSLANGUAGE_DANISH=15;
CSLANGUAGE_DEFAULT=0;
CSLANGUAGE_DUTCH=16;
CSLANGUAGE_ENGLISH_UK=17;
CSLANGUAGE_ENGLISH_US=18;
CSLANGUAGE_ESTONIAN=19;
CSLANGUAGE_FAEROESE=20;
CSLANGUAGE_FARSI=21;
CSLANGUAGE_FINNISH=22;
CSLANGUAGE_FRENCH=23;
CSLANGUAGE_GEORGIAN=24;
CSLANGUAGE_GERMAN=25;
CSLANGUAGE_GREEK=26;
CSLANGUAGE_GUJARATI=27;
CSLANGUAGE_HEBREW=28;
CSLANGUAGE_HINDI=29;
CSLANGUAGE_HUNGARIAN=30;
CSLANGUAGE_ICELANDIC=31;
CSLANGUAGE_INDONESIAN=32;
CSLANGUAGE_ITALIAN=33;
CSLANGUAGE_JAPANESE=34;
CSLANGUAGE_KANNADA=35;
CSLANGUAGE_KASHMIRI=36;
CSLANGUAGE_KAZAK=37;
CSLANGUAGE_KONKANI=38;
CSLANGUAGE_KOREAN=39;
CSLANGUAGE_LATVIAN=40;
CSLANGUAGE_LITHUANIAN=41;
CSLANGUAGE_MACEDONIAN=42;
CSLANGUAGE_MALAY=43;
CSLANGUAGE_MALAYALAM=44;
CSLANGUAGE_MANIPURI=45;
CSLANGUAGE_MARATHI=46;
CSLANGUAGE_NEPALI=47;
CSLANGUAGE_NORWEGIAN=48;
CSLANGUAGE_ORIYA=49;
CSLANGUAGE_POLISH=50;
CSLANGUAGE_PORTUGUESE=51;
CSLANGUAGE_PUNJABI=52;
CSLANGUAGE_ROMANIAN=53;
CSLANGUAGE_RUSSIAN=54;
CSLANGUAGE_SANSKRIT=55;
CSLANGUAGE_SERBIAN=56;
CSLANGUAGE_SINDHI=57;
CSLANGUAGE_SLOVAK=58;
CSLANGUAGE_SLOVENIAN=59;
CSLANGUAGE_SPANISH=60;
CSLANGUAGE_SWAHILI=61;
CSLANGUAGE_SWEDISH=62;
CSLANGUAGE_TAMIL=63;
CSLANGUAGE_TATAR=64;
CSLANGUAGE_TELUGU=65;
CSLANGUAGE_THAI=66;
CSLANGUAGE_TURKISH=67;
CSLANGUAGE_UKRAINIAN=68;
CSLANGUAGE_URDU=69;
CSLANGUAGE_UZBEK=70;
CSLANGUAGE_VIETNAMESE=71;
CSOUND_ERROR=-1;
CSOUND_INITIALIZATION=-2;
CSOUND_MEMORY=-4;
CSOUND_PERFORMANCE=-3;
CSOUND_SIGNAL=-5;
CSOUND_SUCCESS=0;
CSOUNDCFG_BOOLEAN=2
CSOUNDCFG_DOUBLE=4
CSOUNDCFG_FLOAT=3
CSOUNDCFG_INTEGER=1
CSOUNDCFG_INVALID_BOOLEAN=-8
CSOUNDCFG_INVALID_FLAG=-3
CSOUNDCFG_INVALID_NAME=-1
CSOUNDCFG_INVALID_TYPE=-2
CSOUNDCFG_LASTERROR=-10
CSOUNDCFG_MEMORY=-9
CSOUNDCFG_MYFLT=5
CSOUNDCFG_NOT_POWOFTWO=-7
CSOUNDCFG_NULL_POINTER=-4
CSOUNDCFG_POWOFTWO=0x00000001
CSOUNDCFG_STRING=6
CSOUNDCFG_STRING_LENGTH=-10
CSOUNDCFG_SUCCESS=0
CSOUNDCFG_TOO_HIGH=-5
CSOUNDCFG_TOO_LOW=-6
CSOUNDINIT_NO_ATEXIT=2
CSOUNDINIT_NO_SIGNAL_HANDLER=1
CSOUNDMSG_BG_BLACK=(0x0200)
CSOUNDMSG_BG_BLUE=(0x0240)
CSOUNDMSG_BG_COLOR_MASK=(0x0270)
CSOUNDMSG_BG_CYAN=(0x0260)
CSOUNDMSG_BG_GREEN=(0x0220)
CSOUNDMSG_BG_GREY=(0x0270)
CSOUNDMSG_BG_MAGENTA=(0x0250)
CSOUNDMSG_BG_ORANGE=(0x0230)
CSOUNDMSG_BG_RED=(0x0210)
CSOUNDMSG_DEFAULT=(0x0000)
CSOUNDMSG_ERROR=(0x1000)
CSOUNDMSG_FG_ATTR_MASK=(0x0088)
CSOUNDMSG_FG_BLACK=(0x0100)
CSOUNDMSG_FG_BLUE=(0x0104)
CSOUNDMSG_FG_BOLD=(0x0008)
CSOUNDMSG_FG_COLOR_MASK=(0x0107)
CSOUNDMSG_FG_CYAN=(0x0106)
CSOUNDMSG_FG_GREEN=(0x0102)
CSOUNDMSG_FG_MAGENTA=(0x0105)
CSOUNDMSG_FG_RED=(0x0101)
CSOUNDMSG_FG_UNDERLINE=(0x0080)
CSOUNDMSG_FG_WHITE=(0x0107)
CSOUNDMSG_FG_YELLOW=(0x0103)
CSOUNDMSG_ORCH=(0x2000)
CSOUNDMSG_REALTIME=(0x3000)
CSOUNDMSG_TYPE_MASK=(0x7000)
CSOUNDMSG_WARNING=(0x4000)
CSOUND_AUDIO_CHANNEL=2
#CSOUND_CALLBACK_KBD_EVENT=(0x00000001U)
#CSOUND_CALLBACK_KBD_TEXT=(0x00000002U)
CSOUND_CALLBACK_KBD_EVENT=(0x00000001)
CSOUND_CALLBACK_KBD_TEXT=(0x00000002)
CSOUND_CFGVAR_H=
CSOUND_CHANNEL_TYPE_MASK=15
CSOUND_CONTROL_CHANNEL=1
CSOUND_CONTROL_CHANNEL_EXP=3
CSOUND_CONTROL_CHANNEL_INT=1
CSOUND_CONTROL_CHANNEL_LIN=2
CSOUND_EXITJMP_SUCCESS=(256)
#CSOUND_H=
CSOUND_INPUT_CHANNEL=16
#CSOUND_MSG_ATTR_H=
CSOUND_OUTPUT_CHANNEL=32
#CSOUND_SPIN_LOCK=
#CSOUND_SPIN_UNLOCK=
CSOUND_STRING_CHANNEL=3
#CSOUND_SYSDEP_H=
#CSOUND_TEXT_H=
#CSOUND_VERSION_H=

