

dynbind("glpk", "
glp_add_arc(*<_glp_graph>ii)*<_glp_arc>;
glp_add_cols(*<glp_prob>i)i;
glp_add_rows(*<glp_prob>i)i;
glp_add_vertices(*<_glp_graph>i)i;
glp_adv_basis(*<glp_prob>i)v;
glp_analyze_bound(*<glp_prob>i*d*i*d*i)v;
glp_analyze_coef(*<glp_prob>i*d*i*d*d*i*d)v;
glp_asnprob_hall(*<_glp_graph>ii)i;
glp_asnprob_lp(*<glp_prob>i*<_glp_graph>iii)i;
glp_asnprob_okalg(i*<_glp_graph>ii*di)i;
glp_assert_(*c*ci)v;
glp_bf_exists(*<glp_prob>)i;
glp_bf_updated(*<glp_prob>)i;
glp_btran(*<glp_prob>*d)v;
glp_calloc(ii)*v;
glp_check_asnprob(*<_glp_graph>i)i;
glp_check_cnfsat(*<glp_prob>)i;
glp_check_dup(iii*i*i)i;
glp_close_tee()i;
glp_copy_prob(*<glp_prob>*<glp_prob>i)v;
glp_cpp(*<_glp_graph>iii)d;
glp_cpx_basis(*<glp_prob>)v;
glp_create_graph(ii)*<_glp_graph>;
glp_create_index(*<glp_prob>)v;
glp_create_prob()*<glp_prob>;
glp_create_v_index(*<_glp_graph>)v;
glp_del_arc(*<_glp_graph>*<_glp_arc>)v;
glp_del_cols(*<glp_prob>i*i)v;
glp_del_rows(*<glp_prob>i*i)v;
glp_del_vertices(*<_glp_graph>i*i)v;
glp_delete_graph(*<_glp_graph>)v;
glp_delete_index(*<glp_prob>)v;
glp_delete_prob(*<glp_prob>)v;
glp_delete_v_index(*<_glp_graph>)v;
glp_difftime()d;
glp_dual_rtest(*<glp_prob>i*i*did)i;
glp_erase_graph(*<_glp_graph>ii)v;
glp_erase_prob(*<glp_prob>)v;
glp_error_(*ci)*p;
glp_error_hook(*p*v)v;
glp_eval_tab_col(*<glp_prob>i*i*d)i;
glp_eval_tab_row(*<glp_prob>i*i*d)i;
glp_exact(*<glp_prob>*<glp_smcp>)i;
glp_factorize(*<glp_prob>)i;
glp_find_col(*<glp_prob>*c)i;
glp_find_row(*<glp_prob>*c)i;
glp_find_vertex(*<_glp_graph>*c)i;
glp_free(*v)v;
glp_free_env()i;
glp_ftran(*<glp_prob>*d)v;
glp_get_bfcp(*<glp_prob>*<glp_bfcp>)v;
glp_get_bhead(*<glp_prob>i)i;
glp_get_col_bind(*<glp_prob>i)i;
glp_get_col_dual(*<glp_prob>i)d;
glp_get_col_kind(*<glp_prob>i)i;
glp_get_col_lb(*<glp_prob>i)d;
glp_get_col_name(*<glp_prob>i)*c;
glp_get_col_prim(*<glp_prob>i)d;
glp_get_col_stat(*<glp_prob>i)i;
glp_get_col_type(*<glp_prob>i)i;
glp_get_col_ub(*<glp_prob>i)d;
glp_get_dual_stat(*<glp_prob>)i;
glp_get_mat_col(*<glp_prob>i*i*d)i;
glp_get_mat_row(*<glp_prob>i*i*d)i;
glp_get_num_bin(*<glp_prob>)i;
glp_get_num_cols(*<glp_prob>)i;
glp_get_num_int(*<glp_prob>)i;
glp_get_num_nz(*<glp_prob>)i;
glp_get_num_rows(*<glp_prob>)i;
glp_get_obj_coef(*<glp_prob>i)d;
glp_get_obj_dir(*<glp_prob>)i;
glp_get_obj_name(*<glp_prob>)*c;
glp_get_obj_val(*<glp_prob>)d;
glp_get_prim_stat(*<glp_prob>)i;
glp_get_prob_name(*<glp_prob>)*c;
glp_get_rii(*<glp_prob>i)d;
glp_get_row_bind(*<glp_prob>i)i;
glp_get_row_dual(*<glp_prob>i)d;
glp_get_row_lb(*<glp_prob>i)d;
glp_get_row_name(*<glp_prob>i)*c;
glp_get_row_prim(*<glp_prob>i)d;
glp_get_row_stat(*<glp_prob>i)i;
glp_get_row_type(*<glp_prob>i)i;
glp_get_row_ub(*<glp_prob>i)d;
glp_get_sjj(*<glp_prob>i)d;
glp_get_status(*<glp_prob>)i;
glp_get_unbnd_ray(*<glp_prob>)i;
glp_gridgen(*<_glp_graph>iii*i)i;
glp_init_cpxcp(*<glp_cpxcp>)v;
glp_init_env()i;
glp_init_iocp(*<glp_iocp>)v;
glp_init_iptcp(*<glp_iptcp>)v;
glp_init_mpscp(*<glp_mpscp>)v;
glp_init_smcp(*<glp_smcp>)v;
glp_interior(*<glp_prob>*<glp_iptcp>)i;
glp_intfeas1(*<glp_prob>ii)i;
glp_intopt(*<glp_prob>*<glp_iocp>)i;
glp_ios_add_row(*<glp_tree>*ciii*i*did)i;
glp_ios_best_node(*<glp_tree>)i;
glp_ios_branch_upon(*<glp_tree>ii)v;
glp_ios_can_branch(*<glp_tree>i)i;
glp_ios_clear_pool(*<glp_tree>)v;
glp_ios_curr_node(*<glp_tree>)i;
glp_ios_del_row(*<glp_tree>i)v;
glp_ios_get_prob(*<glp_tree>)*<glp_prob>;
glp_ios_heur_sol(*<glp_tree>*d)i;
glp_ios_mip_gap(*<glp_tree>)d;
glp_ios_next_node(*<glp_tree>i)i;
glp_ios_node_bound(*<glp_tree>i)d;
glp_ios_node_data(*<glp_tree>i)*v;
glp_ios_node_level(*<glp_tree>i)i;
glp_ios_pool_size(*<glp_tree>)i;
glp_ios_prev_node(*<glp_tree>i)i;
glp_ios_reason(*<glp_tree>)i;
glp_ios_row_attr(*<glp_tree>i*<glp_attr>)v;
glp_ios_select_node(*<glp_tree>i)v;
glp_ios_terminate(*<glp_tree>)v;
glp_ios_tree_size(*<glp_tree>*i*i*i)v;
glp_ios_up_node(*<glp_tree>i)i;
glp_ipt_col_dual(*<glp_prob>i)d;
glp_ipt_col_prim(*<glp_prob>i)d;
glp_ipt_obj_val(*<glp_prob>)d;
glp_ipt_row_dual(*<glp_prob>i)d;
glp_ipt_row_prim(*<glp_prob>i)d;
glp_ipt_status(*<glp_prob>)i;
glp_load_matrix(*<glp_prob>i*i*i*d)v;
glp_main(i**c)i;
glp_malloc(i)*v;
glp_maxflow_ffalg(*<_glp_graph>iii*dii)i;
glp_maxflow_lp(*<glp_prob>*<_glp_graph>iiii)v;
glp_mem_limit(i)v;
glp_mem_usage(*i*i*<glp_long>*<glp_long>)v;
glp_mincost_lp(*<glp_prob>*<_glp_graph>iiiii)v;
glp_mincost_okalg(*<_glp_graph>iiii*dii)i;
glp_minisat1(*<glp_prob>)i;
glp_mip_col_val(*<glp_prob>i)d;
glp_mip_obj_val(*<glp_prob>)d;
glp_mip_row_val(*<glp_prob>i)d;
glp_mip_status(*<glp_prob>)i;
glp_mpl_alloc_wksp()*<glp_tran>;
glp_mpl_build_prob(*<glp_tran>*<glp_prob>)v;
glp_mpl_free_wksp(*<glp_tran>)v;
glp_mpl_generate(*<glp_tran>*c)i;
glp_mpl_postsolve(*<glp_tran>*<glp_prob>i)i;
glp_mpl_read_data(*<glp_tran>*c)i;
glp_mpl_read_model(*<glp_tran>*ci)i;
glp_netgen(*<_glp_graph>iii*i)i;
glp_open_tee(*c)i;
glp_prim_rtest(*<glp_prob>i*i*did)i;
glp_print_ipt(*<glp_prob>*c)i;
glp_print_mip(*<glp_prob>*c)i;
glp_print_ranges(*<glp_prob>i*ii*c)i;
glp_print_sol(*<glp_prob>*c)i;
glp_printf(*c?)v;
glp_read_asnprob(*<_glp_graph>ii*c)i;
glp_read_ccdata(*<_glp_graph>i*c)i;
glp_read_cnfsat(*<glp_prob>*c)i;
glp_read_graph(*<_glp_graph>*c)i;
glp_read_ipt(*<glp_prob>*c)i;
glp_read_lp(*<glp_prob>*<glp_cpxcp>*c)i;
glp_read_maxflow(*<_glp_graph>*i*ii*c)i;
glp_read_mincost(*<_glp_graph>iiii*c)i;
glp_read_mip(*<glp_prob>*c)i;
glp_read_mps(*<glp_prob>i*<glp_mpscp>*c)i;
glp_read_prob(*<glp_prob>i*c)i;
glp_read_sol(*<glp_prob>*c)i;
glp_rmfgen(*<_glp_graph>*i*ii*i)i;
glp_scale_prob(*<glp_prob>i)v;
glp_sdf_close_file(*<glp_data>)v;
glp_sdf_error(*<glp_data>*c?)v;
glp_sdf_line(*<glp_data>)i;
glp_sdf_open_file(*c)*<glp_data>;
glp_sdf_read_int(*<glp_data>)i;
glp_sdf_read_item(*<glp_data>)*c;
glp_sdf_read_num(*<glp_data>)d;
glp_sdf_read_text(*<glp_data>)*c;
glp_sdf_set_jump(*<glp_data>*v)v;
glp_sdf_warning(*<glp_data>*c?)v;
glp_set_bfcp(*<glp_prob>*<glp_bfcp>)v;
glp_set_col_bnds(*<glp_prob>iidd)v;
glp_set_col_kind(*<glp_prob>ii)v;
glp_set_col_name(*<glp_prob>i*c)v;
glp_set_col_stat(*<glp_prob>ii)v;
glp_set_graph_name(*<_glp_graph>*c)v;
glp_set_mat_col(*<glp_prob>ii*i*d)v;
glp_set_mat_row(*<glp_prob>ii*i*d)v;
glp_set_obj_coef(*<glp_prob>id)v;
glp_set_obj_dir(*<glp_prob>i)v;
glp_set_obj_name(*<glp_prob>*c)v;
glp_set_prob_name(*<glp_prob>*c)v;
glp_set_rii(*<glp_prob>id)v;
glp_set_row_bnds(*<glp_prob>iidd)v;
glp_set_row_name(*<glp_prob>i*c)v;
glp_set_row_stat(*<glp_prob>ii)v;
glp_set_sjj(*<glp_prob>id)v;
glp_set_vertex_name(*<_glp_graph>i*c)v;
glp_simplex(*<glp_prob>*<glp_smcp>)i;
glp_sort_matrix(*<glp_prob>)v;
glp_std_basis(*<glp_prob>)v;
glp_strong_comp(*<_glp_graph>i)i;
glp_term_hook(*p*v)v;
glp_term_out(i)i;
glp_time();
glp_top_sort(*<_glp_graph>i)i;
glp_transform_col(*<glp_prob>i*i*d)i;
glp_transform_row(*<glp_prob>i*i*d)i;
glp_unscale_prob(*<glp_prob>)v;
glp_version()*c;
glp_vprintf(*c*c)v;
glp_warm_up(*<glp_prob>)i;
glp_wclique_exact(*<_glp_graph>i*di)i;
glp_weak_comp(*<_glp_graph>i)i;
glp_write_asnprob(*<_glp_graph>ii*c)i;
glp_write_ccdata(*<_glp_graph>i*c)i;
glp_write_cnfsat(*<glp_prob>*c)i;
glp_write_graph(*<_glp_graph>*c)i;
glp_write_ipt(*<glp_prob>*c)i;
glp_write_lp(*<glp_prob>*<glp_cpxcp>*c)i;
glp_write_maxflow(*<_glp_graph>iii*c)i;
glp_write_mincost(*<_glp_graph>iiii*c)i;
glp_write_mip(*<glp_prob>*c)i;
glp_write_mps(*<glp_prob>i*<glp_mpscp>*c)i;
glp_write_prob(*<glp_prob>i*c)i;
glp_write_sol(*<glp_prob>*c)i;
")
GLPK_H=
GLP_ASN_MAX=2
GLP_ASN_MIN=1
GLP_ASN_MMP=3
GLP_BF_BG=2
GLP_BF_FT=1
GLP_BF_GR=3
GLP_BR_DTH=4
GLP_BR_FFV=1
GLP_BR_LFV=2
GLP_BR_MFV=3
GLP_BR_PCH=5
GLP_BS=1
GLP_BT_BFS=2
GLP_BT_BLB=3
GLP_BT_BPH=4
GLP_BT_DFS=1
GLP_BV=3
GLP_CV=1
GLP_DATA_DEFINED=
GLP_DB=4
GLP_DN_BRNCH=1
GLP_DUAL=3
GLP_DUALP=2
GLP_EBADB=0x01
GLP_EBOUND=0x04
GLP_ECOND=0x03
GLP_EDATA=0x12
GLP_EFAIL=0x05
GLP_EINSTAB=0x11
GLP_EITLIM=0x08
GLP_EMIPGAP=0x0E
GLP_ENOCVG=0x10
GLP_ENODFS=0x0B
GLP_ENOFEAS=0x0F
GLP_ENOPFS=0x0A
GLP_EOBJLL=0x06
GLP_EOBJUL=0x07
GLP_ERANGE=0x13
GLP_EROOT=0x0C
GLP_ERROR_DEFINED=
GLP_ESING=0x02
GLP_ESTOP=0x0D
GLP_ETMLIM=0x09
GLP_FEAS=2
GLP_FR=1
GLP_FX=5
GLP_IBINGO=0x02
GLP_IBRANCH=0x05
GLP_ICUTGEN=0x04
GLP_IHEUR=0x03
GLP_INFEAS=3
GLP_IPREPRO=0x07
GLP_IPT=2
GLP_IROWGEN=0x01
GLP_ISELECT=0x06
GLP_IV=2
GLP_KKT_CS=5
GLP_KKT_DB=4
GLP_KKT_DE=3
GLP_KKT_PB=2
GLP_KKT_PE=1
GLP_LO=2
GLP_LONG_DEFINED=
GLP_MAJOR_VERSION=4
GLP_MAX=2
GLP_MIN=1
GLP_MINOR_VERSION=47
GLP_MIP=3
GLP_MPS_DECK=1
GLP_MPS_FILE=2
GLP_MSG_ALL=3
GLP_MSG_DBG=4
GLP_MSG_ERR=1
GLP_MSG_OFF=0
GLP_MSG_ON=2
GLP_NF=4
GLP_NL=2
GLP_NOFEAS=4
GLP_NO_BRNCH=0
GLP_NS=5
GLP_NU=3
GLP_OFF=0
GLP_ON=1
GLP_OPT=5
GLP_ORD_AMD=2
GLP_ORD_NONE=0
GLP_ORD_QMD=1
GLP_ORD_SYMAMD=3
GLP_PP_ALL=2
GLP_PP_NONE=0
GLP_PP_ROOT=1
GLP_PRIMAL=1
GLP_PROB_DEFINED=
GLP_PT_PSE=0x22
GLP_PT_STD=0x11
GLP_RF_CLQ=4
GLP_RF_COV=3
GLP_RF_CUT=2
GLP_RF_GMI=1
GLP_RF_LAZY=1
GLP_RF_MIR=2
GLP_RF_REG=0
GLP_RT_HAR=0x22
GLP_RT_STD=0x11
GLP_SF_2N=0x20
GLP_SF_AUTO=0x80
GLP_SF_EQ=0x10
GLP_SF_GM=0x01
GLP_SF_SKIP=0x40
GLP_SOL=1
GLP_TRAN_DEFINED=
GLP_TREE_DEFINED=
GLP_UNBND=6
GLP_UNDEF=1
GLP_UP=3
GLP_UP_BRNCH=2

