dynport("SDL")
dynbind("SDL_ttf", "
TTF_ByteSwappedUNICODE(i)v;
TTF_CloseFont(*<_TTF_Font>)v;
TTF_FontAscent(*<_TTF_Font>)i;
TTF_FontDescent(*<_TTF_Font>)i;
TTF_FontFaceFamilyName(*<_TTF_Font>)*c;
TTF_FontFaceIsFixedWidth(*<_TTF_Font>)i;
TTF_FontFaceStyleName(*<_TTF_Font>)*c;
TTF_FontFaces(*<_TTF_Font>)j;
TTF_FontHeight(*<_TTF_Font>)i;
TTF_FontLineSkip(*<_TTF_Font>)i;
TTF_GetFontStyle(*<_TTF_Font>)i;
TTF_GlyphMetrics(*<_TTF_Font>S*i*i*i*i*i)i;
TTF_Init()i;
TTF_Linked_Version()*<SDL_version>;
TTF_OpenFont(*ci)*<_TTF_Font>;
TTF_OpenFontIndex(*cij)*<_TTF_Font>;
TTF_OpenFontIndexRW(*<SDL_RWops>iij)*<_TTF_Font>;
TTF_OpenFontRW(*<SDL_RWops>ii)*<_TTF_Font>;
TTF_Quit()v;
TTF_RenderGlyph_Blended(*<_TTF_Font>S)*<SDL_Surface>;
TTF_RenderGlyph_Shaded(*<_TTF_Font>S)*<SDL_Surface>;
TTF_RenderGlyph_Solid(*<_TTF_Font>S)*<SDL_Surface>;
TTF_RenderText_Blended(*<_TTF_Font>*c)*<SDL_Surface>;
TTF_RenderText_Shaded(*<_TTF_Font>*c)*<SDL_Surface>;
TTF_RenderText_Solid(*<_TTF_Font>*c)*<SDL_Surface>;
TTF_RenderUNICODE_Blended(*<_TTF_Font>*S)*<SDL_Surface>;
TTF_RenderUNICODE_Shaded(*<_TTF_Font>*S)*<SDL_Surface>;
TTF_RenderUNICODE_Solid(*<_TTF_Font>*S)*<SDL_Surface>;
TTF_RenderUTF8_Blended(*<_TTF_Font>*c)*<SDL_Surface>;
TTF_RenderUTF8_Shaded(*<_TTF_Font>*c)*<SDL_Surface>;
TTF_RenderUTF8_Solid(*<_TTF_Font>*c)*<SDL_Surface>;
TTF_SetFontStyle(*<_TTF_Font>i)v;
TTF_SizeText(*<_TTF_Font>*c*i*i)i;
TTF_SizeUNICODE(*<_TTF_Font>*S*i*i)i;
TTF_SizeUTF8(*<_TTF_Font>*c*i*i)i;
TTF_WasInit()i;
")
TTF_GetError=SDL_GetError
TTF_MAJOR_VERSION=2
TTF_MINOR_VERSION=0
TTF_PATCHLEVEL=9
TTF_STYLE_BOLD=0x01
TTF_STYLE_ITALIC=0x02
TTF_STYLE_NORMAL=0x00
TTF_STYLE_UNDERLINE=0x04
TTF_SetError=SDL_SetError

