expect_true(is.externalptr(libm <- dynfind(c("msvcrt", "m", "m.so.6"))))
expect_true(is.externalptr(c_sqrt <- dynsym(libm, "sqrt")))
expect_equal(dyncall(c_sqrt, "d)d", 144), 12)
expect_true(file.exists(dynpath(libm)))
expect_true(is.integer(dyncount(libm)))
expect_true(dyncount(libm) > 0L)
expect_true(is.character(dynlist(libm)))
expect_equal(length(dynlist(libm)), dyncount(libm))
expect_null(dynunload(libm))
