expect_true(is.externalptr(libm <- dynfind(c("msvcrt", "m", "m.so.6"))))
expect_true(is.externalptr(c_sqrt <- dynsym(libm, "sqrt")))
expect_equal(dyncall(c_sqrt, "d)d", 144), 12)
libm_path <- dynpath(libm)
expect_true(is.character(libm_path))
expect_equal(length(libm_path), 1L)
expect_true(file.exists(libm_path) || (Sys.info()[["sysname"]] == "Darwin" && grepl("^/usr/lib/", libm_path)))
expect_true(is.integer(dyncount(libm)))
expect_true(dyncount(libm) > 0L)
libm_symbols <- dynlist(libm)
expect_true(is.character(libm_symbols))
expect_equal(length(libm_symbols), dyncount(libm))
if (Sys.info()[["sysname"]] == "Darwin") {
    expect_false(anyNA(libm_symbols))
    expect_equal(anyDuplicated(libm_symbols), 0L)
    expect_true(all(c("sqrt", "cos", "sin") %in% libm_symbols))
    expect_false(any(c("cache_create", "dispatch_async", "pthread_create") %in% libm_symbols))
    expect_true(length(libm_symbols) > 100L)
    expect_true(length(libm_symbols) < 1000L)
}
expect_null(dynunload(libm))
