TOP	= ../../..
include $(TOP)/build/gmake/prolog.gmake
PYSETUPFLAGS = -I $(TOP)/dyncall:$(TOP)/dynload -L $(TOP)/dyncall/$(BUILD_DIR):$(TOP)/dynload/$(BUILD_DIR) 
PYTHON_SETUP = setup.py
include $(TOP)/build/gmake/epilog.gmake

