; auto-generated by gen-masm.sh
 AREA .text, CODE, ARM64
 EXPORT dcCall_arm64
 EXPORT dcCall_arm64_aggr
dcCall_arm64 PROC
 stp x29, x30, [sp, #-16]!
 mov x29, sp
 ldr d0, [x3,#0 ]
 ldr d1, [x3,#8 ]
 ldr d2, [x3,#16]
 ldr d3, [x3,#24]
 ldr d4, [x3,#32]
 ldr d5, [x3,#40]
 ldr d6, [x3,#48]
 ldr d7, [x3,#56]
 sub sp, sp, x2
 eor x4, x4, x4
 mov x5, x1
 mov x6, sp
dcCall_arm64_next
 cmp x4, x2
 b.ge dcCall_arm64_done
 ldp x7, x9, [x5], #16
 stp x7, x9, [x6], #16
 add x4, x4, 16
 b dcCall_arm64_next
dcCall_arm64_done
 mov x9 , x0
 add x10, x3, 64
 ldr x0, [x10, #0]
 ldr x1, [x10, #8]
 ldr x2, [x10, #16]
 ldr x3, [x10, #24]
 ldr x4, [x10, #32]
 ldr x5, [x10, #40]
 ldr x6, [x10, #48]
 ldr x7, [x10, #56]
 blr x9
 mov sp, x29
 ldp x29, x30, [sp], 16
 ret
 ENDP

dcCall_arm64_aggr PROC
 stp x29, x30, [sp, #-16]!
 mov x29, sp
 sub sp, sp, #16
 str x4, [sp, #0]
 str x5, [sp, #8]
 ldr d0, [x3,#0 ]
 ldr d1, [x3,#8 ]
 ldr d2, [x3,#16]
 ldr d3, [x3,#24]
 ldr d4, [x3,#32]
 ldr d5, [x3,#40]
 ldr d6, [x3,#48]
 ldr d7, [x3,#56]
 sub sp, sp, x2
 eor x4, x4, x4
 mov x5, x1
 mov x6, sp
dcCall_arm64_aggr_next
 cmp x4, x2
 b.ge dcCall_arm64_aggr_done
 ldp x7, x9, [x5], #16
 stp x7, x9, [x6], #16
 add x4, x4, 16
 b dcCall_arm64_aggr_next
dcCall_arm64_aggr_done
 mov x9 , x0
 add x10, x3, 64
 ldr x8, [x29, #-8]
 ldr x0, [x10, #0]
 ldr x1, [x10, #8]
 ldr x2, [x10, #16]
 ldr x3, [x10, #24]
 ldr x4, [x10, #32]
 ldr x5, [x10, #40]
 ldr x6, [x10, #48]
 ldr x7, [x10, #56]
 blr x9
 ldr x10, [x29, #-16]
 cbz x10, dcCall_arm64_aggr_no_ret
 str x0, [x10, #0]
 str x1, [x10, #8]
 str d0, [x10, #16]
 str d1, [x10, #24]
 str d2, [x10, #32]
 str d3, [x10, #40]
dcCall_arm64_aggr_no_ret
 mov sp, x29
 ldp x29, x30, [sp], 16
 ret
 ENDP
 END
