/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_dyncall_DC */

#ifndef _Included_org_dyncall_DC
#define _Included_org_dyncall_DC
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_dyncall_DC
 * Method:    newCallVM
 * Signature: (II)Lorg/dyncall/callvm;
 */
JNIEXPORT jobject JNICALL Java_org_dyncall_DC_newCallVM
  (JNIEnv *, jclass, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
