/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_dyncall_callvm */

#ifndef _Included_org_dyncall_callvm
#define _Included_org_dyncall_callvm
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_dyncall_callvm
 * Method:    reset
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_dyncall_callvm_reset
  (JNIEnv *, jobject);

/*
 * Class:     org_dyncall_callvm
 * Method:    argBool
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_org_dyncall_callvm_argBool
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     org_dyncall_callvm
 * Method:    argByte
 * Signature: (B)V
 */
JNIEXPORT void JNICALL Java_org_dyncall_callvm_argByte
  (JNIEnv *, jobject, jbyte);

/*
 * Class:     org_dyncall_callvm
 * Method:    argShort
 * Signature: (S)V
 */
JNIEXPORT void JNICALL Java_org_dyncall_callvm_argShort
  (JNIEnv *, jobject, jshort);

/*
 * Class:     org_dyncall_callvm
 * Method:    argInt
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_dyncall_callvm_argInt
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_dyncall_callvm
 * Method:    argLong
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_dyncall_callvm_argLong
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_dyncall_callvm
 * Method:    argChar
 * Signature: (C)V
 */
JNIEXPORT void JNICALL Java_org_dyncall_callvm_argChar
  (JNIEnv *, jobject, jchar);

/*
 * Class:     org_dyncall_callvm
 * Method:    argFloat
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_org_dyncall_callvm_argFloat
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     org_dyncall_callvm
 * Method:    argDouble
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_org_dyncall_callvm_argDouble
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     org_dyncall_callvm
 * Method:    argPointer
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_dyncall_callvm_argPointer__J
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_dyncall_callvm
 * Method:    argPointer
 * Signature: (Ljava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_org_dyncall_callvm_argPointer__Ljava_lang_Object_2
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_dyncall_callvm
 * Method:    argString
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_dyncall_callvm_argString
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_dyncall_callvm
 * Method:    callVoid
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_dyncall_callvm_callVoid
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_dyncall_callvm
 * Method:    callInt
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_dyncall_callvm_callInt
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
