# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  workflow_dispatch:
    inputs:
      debug_enabled:
        type: boolean
        description: 'Run the build with tmate debugging enabled'
        required: false
        default: false
      os:
        type: string
        description: 'Only run for specified OS'
        required: false
        default: "all"

name: R-CMD-check

permissions: read-all

jobs:
  R-CMD-check:
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.r }}, ${{ matrix.config.id }})

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: macos-latest,    r: 'release', id: 'macos-arm64'}
          - {os: macos-15-intel,  r: 'release', id: 'macos-intel'}
          - {os: windows-latest,  r: 'release', id: 'windows-release'}
          - {os: windows-latest,  r: 'oldrel-4', id: 'windows-oldrel-4'}
          - {os: ubuntu-latest,   r: 'devel', id: 'ubuntu-devel', http-user-agent: 'release'}
          - {os: ubuntu-latest,   r: 'release', id: 'ubuntu-release'}
          - {os: ubuntu-latest,   r: 'oldrel-1', id: 'ubuntu-oldrel-1'}
          - {os: ubuntu-latest,   r: 'oldrel-4', id: 'ubuntu-oldrel-4'}

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes

    steps:
      - uses: actions/checkout@v6

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}
          http-user-agent: ${{ matrix.config.http-user-agent }}
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::rcmdcheck
          needs: check

      - uses: r-lib/actions/check-r-package@v2
        with:
          upload-snapshots: true
          error-on: '"error"'
          args: 'c("--no-manual", "--no-vignettes")'
          build_args: 'c("--no-manual", "--no-build-vignettes")'

      # Enable tmate debugging of manually-triggered workflows if the input option was provided
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
        if: ${{ github.event_name == 'workflow_dispatch' && inputs.debug_enabled && (inputs.os == matrix.config.os || inputs.os == 'all') && failure() }}
        with:
          limit-access-to-actor: true
